name: Docker Build, Test, and Push

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/simple-site-demo:latest .

      - name: Test Docker image
        run: |
          # Run the Docker container in detached mode
          docker run -d -p 3000:80 --name test-container ${{ secrets.DOCKER_HUB_USERNAME }}/simple-site-demo:latest
          # Wait for the container to start
          sleep 20
          # Use curl to test the container
          curl_output=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:3000)
          # Check if the response is 200 (success)
          if [ "$curl_output" -eq 200 ]; then
            echo "Test passed: Container is serving content successfully."
          else
            echo "Test failed: Container is not serving content as expected."
            exit 1
          fi
          # Stop and remove the container
          docker stop test-container
          docker rm test-container

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/simple-site-demo:latest